const songs=[{id:1,title:"BTS Dynamite Official MV",yt:"https://www.youtube.com/embed/gdZLi9oWNZg",thumb:"https://img.youtube.com/vi/gdZLi9oWNZg/maxresdefault.jpg"},{id:2,title:"Butter Official MV",yt:"https://www.youtube.com/embed/WMweEpGlu_U",thumb:"https://img.youtube.com/vi/WMweEpGlu_U/maxresdefault.jpg"},{id:3,title:"IDOL Official MV",yt:"https://www.youtube.com/embed/pBuZEGg_SF0",thumb:"https://img.youtube.com/vi/pBuZEGg_SF0/maxresdefault.jpg"}];
let watched=JSON.parse(localStorage.getItem('watched'))||[];let streams=parseInt(localStorage.getItem('streams'))||0;let current=null;let customVideos=JSON.parse(localStorage.getItem('customMVs')||"[]");
function openApp(){document.getElementById('landing').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('date').innerText=new Date().toDateString().toUpperCase();updateUI();}
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open');document.getElementById('overlay').classList.toggle('show');}
function updateUI(){const c=document.getElementById('today-count');if(c)c.innerHTML=`${streams} <span>/ 10</span>`; const a=document.getElementById('all-count');if(a)a.innerText=streams; const p=document.getElementById('progress');if(p)p.style.width=Math.min(streams*10,100)+'%';}
function openVid(id){current=[...songs,...customVideos].find(s=>s.id===id||s.yt.includes(id));if(!current)return;document.getElementById('yt').src=current.yt||`https://www.youtube.com/embed/${current.id}`;document.getElementById('video-popup').classList.remove('hidden');}
function closePopup(){document.getElementById('video-popup').classList.add('hidden');document.getElementById('yt').src="";}
function markWatched(){if(current){watched.push({...current,count:1});streams++;localStorage.setItem('watched',JSON.stringify(watched));localStorage.setItem('streams',streams);updateUI();closePopup();}}
function openAddModal(){document.getElementById('addModal').classList.remove('hidden');} function closeAdd(){document.getElementById('addModal').classList.add('hidden');}
function getYTId(url){const m=url.match(/(?:v=|embed\/|youtu\.be\/)([^&\s]+)/);return m?m[1]:null}
function previewYT(url){const id=getYTId(url);if(id){document.getElementById('ytThumb').src=`https://img.youtube.com/vi/${id}/hqdefault.jpg`;document.getElementById('ytPreview').style.display='block';document.getElementById('ytStatus').innerText="Ready ✅";document.getElementById('ytStatus').dataset.id=id;}}
function addVideo(){const id=document.getElementById('ytStatus').dataset.id; if(!id) return; customVideos.push({id:Date.now(),title:`Custom MV ${id}`,yt:`https://www.youtube.com/embed/${id}`,thumb:`https://img.youtube.com/vi/${id}/hqdefault.jpg`}); localStorage.setItem('customMVs',JSON.stringify(customVideos)); closeAdd(); location.reload();}
function openLogin(){document.getElementById('login-popup').classList.remove('hidden');} function closeLogin(){document.getElementById('login-popup').classList.add('hidden');}
function doLogin(){const e=document.getElementById('email').value; if(!e) return; localStorage.setItem('user_email',e); location.reload();}
function loadUser(){const e=localStorage.getItem('user_email'); if(e){const n=e.split('@')[0]; document.getElementById('user-name-display')&&(document.getElementById('user-name-display').innerText=n); document.getElementById('welcome-name')&&(document.getElementById('welcome-name').innerText=n);}}
document.addEventListener('DOMContentLoaded',()=>{loadUser(); updateUI(); const ml=document.getElementById('music-list'); if(ml){ml.innerHTML=[...songs,...customVideos].map(s=>`<div class="music-card" onclick="openVid('${s.id}')"><img src="${s.thumb}"><div class="music-body"><h4 style="font-size:13px">${s.title}</h4></div></div>`).join('');}});
